### ISSUE TITLE
UI: use padding instead of margin for Uptime section

### ISSUE THREAD

**Issue by atinux** [zernonia/statusbase#6]
This way, we always have one selected when we hover, this is a much better UX and this will keep the spacing working.

https://user-images.githubusercontent.com/904724/170997853-9146e914-6466-4273-88fa-6e8b8834533d.mp4

By hacking in the devtools around it and adding:

```css
[data-v-tippy] {
    padding: 0.3em;
    cursor: pointer;
}
```

It looks like this:

https://user-images.githubusercontent.com/904724/170998295-42392899-94d9-4770-904a-caf7210e1bed.mp4
